export const FETCH_ARTISTS = "FETCH_ARTISTS";
export const SORT_BY_ALBUM = "SORT_BY_ALBUM";
export const SORT_BY_RELEASE = "SORT_BY_RELEASE";
export const GET_SONG_DETAILS = "GET_SONG_DETAILS";
export const TRIGGER_MODAL = "TRIGGER_MODAL";
